# The west manifest file for NCS Bare Metal

manifest:
  defaults:
    remote: ncs

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  group-filter:
    - -nrf-bm-internal

  projects:
    - name: nrf
      repo-path: sdk-nrf
      revision: e39855b1d4494e4cd9b16a2b39110f4c701d10b4
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - dragoon
          - hal_nordic
          - lz4
          - mbedtls
          - mcuboot
          - nrfxlib
          - picolibc
          - oberon-psa-crypto
          - qcbor
          - segger
          - tinycrypt
          - zephyr
          - cmock
    - name: sdk-nrf-bm-internal
      path: nrf-bm-internal
      revision: pull/6/head
      groups:
        - nrf-bm-internal

  self:
    path: nrf-bm
