# The west manifest file for NCS Lite

manifest:
  defaults:
    remote: ncs

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  group-filter:
    - -ncs-lite-internal

  projects:
    - name: sdk-nrf
      path: nrf
      revision: 42f0799cf00546256b2e8f079361be3b821b0c4f
      import:
        name-allowlist:
          - cmsis
          - dragoon
          - hal_nordic
          - lz4
          - mbedtls
          - mcuboot
          - nrfxlib
          - picolibc
          - oberon-psa-crypto
          - qcbor
          - segger
          - tinycrypt
          - zephyr
          - cmock
    - name: sdk-ncs-lite-internal
      path: ncs-lite-internal
      revision: 2086b4bb5ee2cc68b824fe5ecd4e2461987e4c5c
      groups:
        - ncs-lite-internal

  self:
    path: nrf-lite
