# The west manifest file for NCS Bare Metal

manifest:
  defaults:
    remote: ncs

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      repo-path: sdk-nrf
      revision: v3.4.0
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - dragoon
          - hal_nordic
          - lz4
          - mbedtls
          - mcuboot
          - nrfxlib
          - picolibc
          - oberon-psa-crypto
          - qcbor
          - segger
          - tinycrypt
          - zephyr
          - cmock
          - zcbor

  self:
    path: nrf-bm
