# The west manifest file for NCS Bare Metal

manifest:
  defaults:
    remote: ncs

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  group-filter:
    - -nrf-bm-internal

  projects:
    - name: nrf
      repo-path: sdk-nrf
      revision: e9101127fc24a4bd5bf1b3067c78093182038d02
      import:
        name-allowlist:
          - cmsis_6
          - dragoon
          - hal_nordic
          - lz4
          - mbedtls
          - mcuboot
          - nrfxlib
          - picolibc
          - oberon-psa-crypto
          - qcbor
          - segger
          - tinycrypt
          - zephyr
          - cmock
          - zcbor
    - name: sdk-nrf-bm-internal
      path: nrf-bm-internal
      revision: 2086b4bb5ee2cc68b824fe5ecd4e2461987e4c5c
      groups:
        - nrf-bm-internal

  self:
    path: nrf-bm
