# The west manifest file for NCS Lite

manifest:
  defaults:
    remote: ncs

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: eivindj-nordic
      url-base: https://github.com/eivindj-nordic

  group-filter:
    - -nrf-lite-internal

  projects:
    - name: sdk-nrf
      path: nrf
      revision: 42f0799cf00546256b2e8f079361be3b821b0c4f
      import:
        name-allowlist:
          - cmsis
          - dragoon
          - hal_nordic
          - lz4
          - mbedtls
          - mcuboot
          - nrfxlib
          - picolibc
          - oberon-psa-crypto
          - qcbor
          - segger
          - tinycrypt
          - zephyr
          - cmock
    - name: nrf-lite-internal
      remote: eivindj-nordic
      revision: main
      groups:
        - nrf-lite-internal

  self:
    path: nrf-lite
