# The west manifest file for NCS Bare Metal

manifest:
  defaults:
    remote: ncs

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  group-filter:
    - -nrf-bm-internal

  projects:
    - name: nrf
      repo-path: sdk-nrf
      revision: 46768adeb8a4cb95ed582f1b07166f975f0ff524
      import:
        name-allowlist:
          - cmsis_6
          - dragoon
          - hal_nordic
          - lz4
          - mbedtls
          - mcuboot
          - nrfxlib
          - picolibc
          - oberon-psa-crypto
          - qcbor
          - segger
          - tinycrypt
          - zephyr
          - cmock
          - zcbor
    - name: sdk-nrf-bm-internal
      path: nrf-bm-internal
      revision: pull/6/head
      groups:
        - nrf-bm-internal

  self:
    path: nrf-bm
