# Logging
CONFIG_LOG=y
CONFIG_LOG_BACKEND_BM_UARTE=y

# Enabling SoftDevice is not strictly needed, though we are building with SoftDevice boards.
CONFIG_SOFTDEVICE=y

# Buttons, LEDs and timer
CONFIG_BM_BUTTONS=y
CONFIG_BM_GPIOTE=y
CONFIG_BM_TIMER=y

# HFCLK and related clock services for SoC peripherals.
CONFIG_CLOCK_CONTROL=y

# SPIM hardware driver, required by bm_spi_mngr for SPI master transfers.
CONFIG_NRFX_SPIM=y
# Queued SPI transactions on top of nrfx SPIM.
CONFIG_BM_SPI_MNGR=y
