# Logging
CONFIG_LOG=y
CONFIG_LOG_BACKEND_BM_UARTE=y
CONFIG_SAMPLE_SHELL_BM_UARTE_LOG_LEVEL_INF=y

# Shell
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_BM_UARTE=y

# Optional shell features
CONFIG_SHELL_HELP=y
CONFIG_SHELL_TAB=y
CONFIG_SHELL_TAB_AUTOCOMPLETION=y
CONFIG_SHELL_HISTORY=y
