#
# Copyright (c) 2026 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Logging
CONFIG_LOG=y
CONFIG_LOG_BACKEND_BM_UARTE=y

# Shell
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_BM_UARTE=y

# Optional shell features
CONFIG_SHELL_HELP=y
CONFIG_SHELL_TAB=y
CONFIG_SHELL_TAB_AUTOCOMPLETION=y
CONFIG_SHELL_HISTORY=y

# HW used by radio_test
CONFIG_NRFX_TIMER=y
CONFIG_NRFX_GPPI=y

# Use fake PRNG to reduce HW dependencies
CONFIG_TEST_RANDOM_GENERATOR=y

# Disable SoftDevice.
# The radio_test sample needs to control radio and other relevant periperhals on its own.
CONFIG_SOFTDEVICE=n
