name: Checkpatch

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  checkpatch:
    runs-on: ubuntu-latest
    name: Run checkpatch script on PR

    steps:
      - name: Checkout the code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          path: .
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: cache-pip
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-doc-pip

      - name: Run checkpatch
        continue-on-error: false
        id: checkpatch
        env:
          BASE_REF: ${{ github.base_ref }}
        working-directory: .
        run: |
          git diff origin/${BASE_REF} | scripts/checkpatch.pl --no-tree --ignore COMPLEX_MACRO -
