name: License Check

on: pull_request

jobs:
  license_job:
    runs-on: ubuntu-24.04
    name: Run license checks on patch series (PR)
    steps:
    - name: Checkout the code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        path: ncs/nrf-bm
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: cache-pip
      uses: actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f # v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-doc-pip

    - name: Install python dependencies
      run: |
        pip3 install -U pip
        pip3 install -U setuptools
        export PATH="$HOME/.local/bin:$PATH"
        pip3 install -U wheel
        pip3 install --user -U west
        pip3 show -f west

    - name: Prepare west project
      working-directory: ncs
      run: |
        west init -l nrf-bm
        west update -o=--depth=1 -n

    - name: West zephyr-export
      working-directory: ncs
      env:
        PR_REF: ${{ github.event.pull_request.head.sha }}
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        export PATH="$HOME/bin:$PATH"
        west zephyr-export
        echo "ZEPHYR_BASE=$(pwd)/zephyr" >> $GITHUB_ENV
        # debug
        ( cd nrf-bm; echo "nrf-bm"; git log --pretty=oneline --max-count=10 )
        ( cd nrf; echo "nrf"; git log --pretty=oneline --max-count=10 )
        ( cd zephyr; echo "zephyr"; git log --pretty=oneline --max-count=10 )

    - name: Install license check script dependencies
      run: |
        pip3 install -U -r ncs/nrf/scripts/ci/requirements.txt

    - name: Run license checks
      id: license_checks
      env:
        BASE_REF: ${{ github.base_ref }}
        ZEPHYR_BASE: ${{ env.ZEPHYR_BASE }}
      working-directory: ncs/nrf-bm
      if: contains(github.event.pull_request.user.login, 'dependabot[bot]') != true
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        export PATH="$HOME/bin:$PATH"
        ${ZEPHYR_BASE}/../nrf/scripts/ci/check_license.py \
            --github \
            -l ${ZEPHYR_BASE}/../nrf-bm/scripts/ci/license_allow_list.yaml \
            -c origin/${BASE_REF}..

    - name: Upload results
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
      continue-on-error: true
      if: always() && contains(github.event.pull_request.user.login, 'dependabot[bot]') != true
      with:
        name: licenses.xml
        path: ncs/nrf-bm/licenses.xml
        overwrite: true
